services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nemotron-vllm
    restart: unless-stopped
    gpus: all
    privileged: true
    ipc: host

    ports:
      - "8000:8000"

    environment:
      HF_TOKEN: "${HF_TOKEN}"
      VLLM_TEST_FORCE_FP8_MARLIN: "1"
      VLLM_LOGGING_LEVEL: "INFO"
      VLLM_DEBUG_LOG_SERVER_RESPONSE: "TRUE"

    volumes:
      - "${HOME}/.cache/huggingface:/root/.cache/huggingface"

    command:
      - nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-NVFP4
      - --mamba-backend
      - flashinfer
      - --enable-prefix-caching
      - --max-num-batched-tokens
      - "16384"
      - --kv-cache-dtype
      - fp8
      - --moe-backend
      - marlin
      - --attention-backend
      - FLASHINFER
      - --linear-backend
      - marlin
      - --attention-config
      - '{"use_trtllm_attention":true}'
      - --enable-flashinfer-autotune
      - --mamba-cache-mode
      - none
      - --async-scheduling
      - --enable-chunked-prefill
      - --gpu-memory-utilization
      - "0.8"
      - --load-format
      - instanttensor
      - --safetensors-load-strategy
      - prefetch
      - --tensor-parallel-size
      - "1"
      - --reasoning-parser
      - nemotron_v3
      - --mamba-ssm-cache-dtype
      - float16
      - --enable-mamba-cache-stochastic-rounding
      - --mamba-cache-philox-rounds
      - "5"
      - --enable-auto-tool-choice
      - --enable-log-requests
      - --enable-log-outputs
      - --tool-call-parser
      - qwen3_xml
