# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "switchyard-py"
version.workspace = true
description = "PyO3 bindings for Switchyard Rust crates"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "_switchyard_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
futures.workspace = true
http.workspace = true
switchyard-libsy.workspace = true
pyo3 = { version = "0.28.3", features = ["abi3-py310"] }
pyo3-async-runtimes = { version = "0.28", features = ["tokio-runtime"] }
pythonize = "0.28.0"
serde.workspace = true
serde_json.workspace = true
switchyard-protocol.workspace = true
switchyard-server.workspace = true
tokio.workspace = true
